version: '3'

services:
  templateapi:
    container_name: accountmoduleservice
    image: accountmoduleservice-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    restart: always
    environment:
      - SPRING.DATASOURCE.URL=${DATASOURCE_URL}
      - SPRING.DATASOURCE.USERNAME=${DATASOURCE_USER}
      - SPRING.DATASOURCE.PASSWORD=${DATASOURCE_PASS}
